version: '3.8'

x-worker-template: &worker-template
  build:
    context: .
    dockerfile: dockerfiles/web_app/Dockerfile
  entrypoint: celery
  command: -A celery_app.app worker --loglevel=info
  volumes:
    - ./core:/core
  depends_on:
    - redis
    - database
  environment:
    - DB_HOST=localhost
    - DB_PORT=5432
    - DB_NAME=dbname
    - DB_USER=dbuser
    - DB_PASS=password
    - REDIS_URL=redis://localhost:6379/0
  network_mode: "host"

services:
  web-app:
    build:
      context: .
      dockerfile: dockerfiles/web_app/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./core:/core
    environment:
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password
      - IS_DEBUG=True
      - REDIS_URL=redis://localhost:6379/0
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - redis
      - database
    network_mode: "host"

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data
    network_mode: "host"

  redis:
    image: redis:7.0.5-alpine
    network_mode: "host"

  worker1:
    <<: *worker-template
  worker2:
    <<: *worker-template
  worker3:
    <<: *worker-template
  worker4:
    <<: *worker-template

volumes:
  db_data:
