version: '3.8'

x-worker-template: &worker-template
  build:
    context: .
    dockerfile: dockerfiles/web_app/Dockerfile
  entrypoint: celery
  command: -A celery_app.app worker --loglevel=info
  volumes:
    - ./core:/core
  depends_on:
    - redis
    - database
  environment:
    - DB_HOST=database
    - DB_NAME=dbname
    - DB_USER=dbuser
    - DB_PASS=password

services:
  web-app:
    build:
      context: .
      dockerfile: dockerfiles/web_app/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./core:/core
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password
      - IS_DEBUG=True
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8002"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker1:
    <<: *worker-template
    hostname: worker1
  worker2:
    <<: *worker-template
    hostname: worker2
  worker3:
    <<: *worker-template
    hostname: worker3
  worker4:
    <<: *worker-template
    hostname: worker4

  flower:
    build:
      context: .
      dockerfile: dockerfiles/web_app/Dockerfile
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./core:/core
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

volumes:
  db_data:
