version: '3.8'

x-worker-template: &worker-template
  build:
    context: .
  entrypoint: celery
  command: -A celery_app.app worker --loglevel=info
  volumes:
    - ./core:/core
    - ./core/static:/static
  depends_on:
    - redis
    - database
  environment:
    - DB_HOST=database
    - DB_NAME=dbname
    - DB_USER=dbuser
    - DB_PASS=password

services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./core/static:/static/
      - ./core:/core
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=password
    command: >
      sh -c "gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker1:
    <<: *worker-template
    hostname: worker1
  worker2:
    <<: *worker-template
    hostname: worker2
  worker3:
    <<: *worker-template
    hostname: worker3
  worker4:
    <<: *worker-template
    hostname: worker4

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./core:/core
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./core/static:/static/
      - ./certs:/etc/nginx/certs
    ports:
      - '80:80'
    depends_on:
      - web-app

volumes:
  db_data:
