# Generated by Django 5.0.7 on 2024-08-04 11:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AddField(
            model_name='user',
            name='image_identifier',
            field=models.UUIDField(default=uuid.UUID('e6511577-23f5-4d63-9a7a-9f0cd208bcab'), editable=False, help_text='uuid for image', unique=True),
        ),
    ]
