# Generated by Django 5.0.7 on 2024-11-11 14:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_identifier',
            field=models.UUIDField(default=uuid.UUID('13f058d7-d6e3-46a0-afde-83da17d9920f'), editable=False, help_text='uuid for image', unique=True),
        ),
    ]
