# Generated by Django 5.0.7 on 2024-08-08 08:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_user_city_alter_user_image_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_identifier',
            field=models.UUIDField(default=uuid.UUID('82d39f18-10cf-407b-aa18-aebefd30af13'), editable=False, help_text='uuid for image', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('id', 'title')},
        ),
    ]
