# Generated by Django 5.0.7 on 2024-08-08 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_user_image_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_identifier',
            field=models.UUIDField(default=uuid.UUID('46dfbb80-2ee1-4da2-a286-170fa105e00a'), editable=False, help_text='uuid for image', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('user', 'title')},
        ),
    ]
