# Generated by Django 5.0.7 on 2024-09-05 04:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_alter_user_email_alter_user_image_identifier'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email filed'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_identifier',
            field=models.UUIDField(default=uuid.UUID('a5dea88a-f9da-48f7-a809-2c854244dd57'), editable=False, help_text='uuid for image', unique=True),
        ),
    ]
