# Generated by Django 5.0.7 on 2024-09-05 04:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_user_managers_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_identifier',
            field=models.UUIDField(default=uuid.UUID('85601df4-5a4d-4416-9f85-e1eaa3ed61fa'), editable=False, help_text='uuid for image', unique=True),
        ),
    ]
