# Generated by Django 5.0.7 on 2024-09-05 04:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_alter_user_image_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='image_identifier',
            field=models.UUIDField(default=uuid.UUID('9f871f3d-9bd9-490a-9350-e0848ee53e59'), editable=False, help_text='uuid for image', unique=True),
        ),
    ]
