# Generated by Django 5.0.7 on 2024-10-05 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_alter_user_image_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_identifier',
            field=models.UUIDField(default=uuid.UUID('b7743943-71fb-4d4b-9c73-3627f6c0aff4'), editable=False, help_text='uuid for image', unique=True),
        ),
    ]
