# Generated by Django 5.0.7 on 2024-10-05 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_alter_user_image_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_identifier',
            field=models.UUIDField(default=uuid.UUID('44890404-fd74-44c4-90c9-8c0af65fcce9'), editable=False, help_text='uuid for image', unique=True),
        ),
    ]
