# Generated by Django 5.0.7 on 2024-11-12 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0014_alter_user_image_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_identifier',
            field=models.UUIDField(default=uuid.UUID('05a35859-e47c-4d39-b69d-bdd53ba1b869'), editable=False, help_text='uuid for image', unique=True),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_message_ring', models.BooleanField(default=True)),
                ('chat_message_in_browser', models.BooleanField(default=True)),
                ('is_executor_ring', models.BooleanField(default=True)),
                ('is_executor_in_browser', models.BooleanField(default=True)),
                ('dl_expired_ring', models.BooleanField(default=True)),
                ('dl_expired_in_browser', models.BooleanField(default=True)),
                ('task_done_ring', models.BooleanField(default=True)),
                ('task_done_in_browser', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before_start_task', models.IntegerField(choices=[(1, 'За 1 день до'), (2, 'За 2 день до'), (3, 'За 3 день до')], default=1)),
                ('exact_time_of_day_before_start_task', models.IntegerField(choices=[(1, '1:00'), (2, '2:00'), (3, '3:00'), (4, '4:00'), (5, '5:00'), (6, '6:00'), (7, '7:00'), (8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00')], default=8)),
                ('time_before_deadline', models.IntegerField(choices=[(1, 'За 1 минут до'), (2, 'За 2 минут до'), (3, 'За 3 минут до'), (4, 'За 4 минут до'), (5, 'За 5 минут до'), (6, 'За 6 минут до'), (7, 'За 7 минут до'), (8, 'За 8 минут до'), (9, 'За 9 минут до'), (10, 'За 10 минут до'), (11, 'За 11 минут до'), (12, 'За 12 минут до'), (13, 'За 13 минут до'), (14, 'За 14 минут до'), (15, 'За 15 минут до'), (16, 'За 16 минут до'), (17, 'За 17 минут до'), (18, 'За 18 минут до'), (19, 'За 19 минут до'), (20, 'За 20 минут до'), (21, 'За 21 минут до'), (22, 'За 22 минут до'), (23, 'За 23 минут до'), (24, 'За 24 минут до'), (25, 'За 25 минут до'), (26, 'За 26 минут до'), (27, 'За 27 минут до'), (28, 'За 28 минут до'), (29, 'За 29 минут до'), (30, 'За 30 минут до'), (31, 'За 31 минут до'), (32, 'За 32 минут до'), (33, 'За 33 минут до'), (34, 'За 34 минут до'), (35, 'За 35 минут до'), (36, 'За 36 минут до'), (37, 'За 37 минут до'), (38, 'За 38 минут до'), (39, 'За 39 минут до'), (40, 'За 40 минут до'), (41, 'За 41 минут до'), (42, 'За 42 минут до'), (43, 'За 43 минут до'), (44, 'За 44 минут до'), (45, 'За 45 минут до'), (46, 'За 46 минут до'), (47, 'За 47 минут до'), (48, 'За 48 минут до'), (49, 'За 49 минут до'), (50, 'За 50 минут до'), (51, 'За 51 минут до'), (52, 'За 52 минут до'), (53, 'За 53 минут до'), (54, 'За 54 минут до'), (55, 'За 55 минут до'), (56, 'За 56 минут до'), (57, 'За 57 минут до'), (58, 'За 58 минут до'), (59, 'За 59 минут до')], default=30)),
                ('remind_about_expire_in', models.CharField(choices=[('В начале следующей недели', 'В начале следующей недели')], default='В начале следующей недели')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
            },
        ),
    ]
