# Generated by Django 5.0.7 on 2024-11-14 05:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0015_alter_user_image_identifier_notifications_reminders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_identifier',
            field=models.UUIDField(default=uuid.UUID('15d23495-4fb3-4eb9-8e5d-de6a4922d863'), editable=False, help_text='uuid for image', unique=True),
        ),
    ]
