# Generated by Django 5.0.7 on 2024-11-14 06:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0016_alter_user_image_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_identifier',
            field=models.UUIDField(default=uuid.UUID('afd5b1ef-e56f-4197-a1d8-e81d6c5993d5'), editable=False, help_text='uuid for image', unique=True),
        ),
    ]
