# Generated by Django 5.0.7 on 2024-12-03 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0019_alter_user_image_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_phone',
            field=models.CharField(blank=True, max_length=25, null=True, validators=[django.core.validators.RegexValidator('^((8|\\+7)[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='otchestwo',
            field=models.CharField(blank=True, max_length=150, verbose_name='otchestwo'),
        ),
    ]
