# Generated by Django 5.0.7 on 2024-12-10 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0020_user_business_phone_user_otchestwo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.PositiveSmallIntegerField(choices=[(0, 'discord'), (1, 'vk'), (2, 'telegram'), (3, 'skype')], default=2, max_length=255, verbose_name='url name'),
        ),
    ]
