# Generated by Django 5.0.7 on 2024-12-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0022_alter_link_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=255, verbose_name='gender'),
        ),
    ]
