# Generated by Django 5.0.7 on 2024-12-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0021_user_email_verified'),
        ('user_profile', '0023_user_gender'),
    ]

    operations = [
    ]
