# Generated by Django 5.0.7 on 2024-12-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0024_merge_0021_user_email_verified_0023_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.PositiveSmallIntegerField(verbose_name='url name'),
        ),
    ]
