# Generated by Django 5.0.7 on 2024-12-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0025_remove_user_gender_alter_link_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=255, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.PositiveSmallIntegerField(choices=[(0, 'discord'), (1, 'vk'), (2, 'telegram'), (3, 'skype')], default=2, verbose_name='url name'),
        ),
    ]
